// Shaders GLSL, chargés comme texte brut par Vite (?raw).

import GLSL_COMMON_SRC from './common.glsl?raw';
import GLSL_ART_SRC from './art.glsl?raw';
import CARD_VS_SRC from './card/card.vs.glsl?raw';
import CARD_FS_SRC from './card/card.fs.glsl?raw';
import BACK_FS_SRC from './card/back.fs.glsl?raw';
import EDGE_VS_SRC from './card/edge.vs.glsl?raw';
import EDGE_FS_SRC from './card/edge.fs.glsl?raw';
import PACK_TEAR_SRC from './pack/tear.glsl?raw';
import PACK_VS_SRC from './pack/pack.vs.glsl?raw';
import STRIP_VS_SRC from './pack/strip.vs.glsl?raw';
import PACK_FS_SRC from './pack/pack.fs.glsl?raw';
import LEAK_VS_SRC from './pack/leak.vs.glsl?raw';
import LEAK_FS_SRC from './pack/leak.fs.glsl?raw';
import SKY_VS_SRC from './sky/sky.vs.glsl?raw';
import SKY_FS_SRC from './sky/sky.fs.glsl?raw';
import CLINE_VS_SRC from './sky/con-line.vs.glsl?raw';
import CLINE_FS_SRC from './sky/con-line.fs.glsl?raw';
import CSTAR_VS_SRC from './sky/con-star.vs.glsl?raw';
import CSTAR_FS_SRC from './sky/con-star.fs.glsl?raw';
import PART_VS_SRC from './fx/particles.vs.glsl?raw';
import PART_FS_SRC from './fx/particles.fs.glsl?raw';
import QUAD_VS_SRC from './fx/quad.vs.glsl?raw';
import RAYS_FS_SRC from './fx/rays.fs.glsl?raw';
import FLARE_FS_SRC from './fx/flare.fs.glsl?raw';
import FS_VS_SRC from './post/fullscreen.vs.glsl?raw';
import DOWN_FS_SRC from './post/kawase-down.fs.glsl?raw';
import UP_FS_SRC from './post/kawase-up.fs.glsl?raw';
import COMP_FS_SRC from './post/composite.fs.glsl?raw';

export const GLSL_COMMON: string = GLSL_COMMON_SRC;
export const GLSL_ART: string = GLSL_ART_SRC;
export const CARD_VS: string = CARD_VS_SRC;
export const CARD_FS: string = CARD_FS_SRC;
export const BACK_FS: string = BACK_FS_SRC;
export const EDGE_VS: string = EDGE_VS_SRC;
export const EDGE_FS: string = EDGE_FS_SRC;
export const PACK_TEAR: string = PACK_TEAR_SRC;
export const PACK_VS: string = PACK_VS_SRC;
export const STRIP_VS: string = STRIP_VS_SRC;
export const PACK_FS: string = PACK_FS_SRC;
export const LEAK_VS: string = LEAK_VS_SRC;
export const LEAK_FS: string = LEAK_FS_SRC;
export const SKY_VS: string = SKY_VS_SRC;
export const SKY_FS: string = SKY_FS_SRC;
export const CLINE_VS: string = CLINE_VS_SRC;
export const CLINE_FS: string = CLINE_FS_SRC;
export const CSTAR_VS: string = CSTAR_VS_SRC;
export const CSTAR_FS: string = CSTAR_FS_SRC;
export const PART_VS: string = PART_VS_SRC;
export const PART_FS: string = PART_FS_SRC;
export const QUAD_VS: string = QUAD_VS_SRC;
export const RAYS_FS: string = RAYS_FS_SRC;
export const FLARE_FS: string = FLARE_FS_SRC;
export const FS_VS: string = FS_VS_SRC;
export const DOWN_FS: string = DOWN_FS_SRC;
export const UP_FS: string = UP_FS_SRC;
export const COMP_FS: string = COMP_FS_SRC;
