uniform sampler2D uLayout;
uniform sampler2D uMask;
uniform vec2 uTexel;
uniform float uAspect;
uniform float uGlow;
uniform vec3 uGlowCol;
uniform float uFlash;
uniform float uDim;
uniform float uSweep;
varying vec2 vUv; varying vec3 vPosV; varying vec3 vNrmV; varying vec3 vTanV; varying vec3 vBitV;
void main(){
  vec4 lay = texture2D(uLayout, vUv);
  vec4 msk = texture2D(uMask, vUv);
  vec3 V = normalize(-vPosV);
  vec3 N = normalize(vNrmV), T = normalize(vTanV), B = normalize(vBitV);
  float hL = texture2D(uMask, vUv - vec2(uTexel.x*1.5, 0.)).r;
  float hR = texture2D(uMask, vUv + vec2(uTexel.x*1.5, 0.)).r;
  float hD = texture2D(uMask, vUv - vec2(0., uTexel.y*1.5)).r;
  float hU = texture2D(uMask, vUv + vec2(0., uTexel.y*1.5)).r;
  vec3 nt = normalize(vec3((hL - hR)*1.3, (hD - hU)*1.3, 1.));
  vec3 Nf = normalize(nt.x*T + nt.y*B + nt.z*N);
  vec3 Rf = reflect(-V, Nf), Rc = reflect(-V, N);
  float fres = pow(1. - clamp(dot(N, V), 0., 1.), 5.);
  vec3 Lk = normalize(vec3(-.45, .6, .66));
  vec3 e = envMap(Rf);
  vec3 gold = vec3(1., .76, .36);
  vec3 col = lay.rgb*(.8 + .3*max(dot(Nf, Lk), 0.));
  col = mix(col, e*mix(gold, vec3(1., .95, .85), fres*.5) + gold*.04, msk.r);
  col += e*gold*msk.g*.3;
  float spec = pow(max(dot(Rc, Lk), 0.), 90.)*.45 + pow(max(dot(Rc, normalize(vec3(.05, .1, 1.))), 0.), 500.)*.15;
  col += vec3(1., .97, .94)*spec + envMap(Rc)*fres*.22;
  float sw = exp(-pow((vUv.x*uAspect + vUv.y*.6 - uSweep)*4., 2.));
  col += vec3(1.)*sw*.35*(.25 + msk.r);
  vec2 ed = min(vUv, 1. - vUv)*vec2(uAspect, 1.);
  float edge = min(ed.x, ed.y);
  col += uGlowCol*uGlow*(exp(-edge*26.)*1.8 + .12);
  col += vec3(1.)*uFlash;
  col *= 1. - uDim*.74;
  gl_FragColor = vec4(col, 1.);
}
